pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git credentialsId: 'e9f0a9fd-bacc-43e2-9056-74448366e0a8', url: 'https://github.com/hermannbrice12/Projet-Docker-Kubernetes.git'
            }
        }
    }
}
 stage('Test') {
            steps {
                script {
                    docker.image("${params.DOCKER_IMAGE}:${params.DOCKER_TAG}").inside {
                        sh 'echo "Running tests inside the container..."'
                        
                    }
                }
            }
        }