pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git credentialsId: 'e9f0a9fd-bacc-43e2-9056-74448366e0a8', url: 'https://github.com/hermannbrice12/Projet-Docker-Kubernetes.git'
            }
        }
    }
}
 stage('Test') {
            steps {
                script {
                    docker.image("${params.DOCKER_IMAGE}:${params.DOCKER_TAG}").inside {
                        sh 'echo "Running tests inside the container..."'
                        
                    }
                }
            }
        }

        stage('Push') {
            steps {
                // Push the Docker image to Docker Hub
                script {
                    docker.withRegistry('', 'docker-hub-credentials') {
                        docker.image("${DOCKER_IMAGE}").push('latest')
                    }
                }
            }
        }

        stage('Clean Up') {
            steps {
                // Clean up the Docker environment
                sh 'docker rmi ${DOCKER_IMAGE}'
            }
        }
    
post {
        always {
            // Clean up the workspace after the build
            deleteDir()
        }
    }
